library(readxl)
diabetest1 <- read_excel("C:/Users/hk838/Downloads/NARA.xlsx")
A <- c(diabetest1$Age)
Mean <- mean(A)
print(Mean)
Minimum <- min(A)
print(Minimum)
Maximum <- max(A)
print(Maximum)
MinMax <- (A - Minimum) / (Maximum - Minimum)
print(MinMax)